const llmService = require('./llmService');

class AITextDetector {
  async detect(postData) {
    const text = `${postData.title || ''}\n\n${postData.body || ''}`.trim();
    if (!text) {
      return {
        aiProbability: 0.1,
        isLikelyAI: false,
        confidence: "low",
        indicators: ["No text content available"],
        aiScore: 90
      };
    }

    // Try LLM detection
    try {
      const systemPrompt = `Analyze the following Reddit post text and determine if it was generated by an AI model (like ChatGPT/Claude/LLM) or written by a human.
Return JSON with format:
{
  "aiProbability": number (0.0 to 1.0),
  "isLikelyAI": boolean,
  "confidence": "high|medium|low",
  "indicators": ["string"],
  "explanation": "string"
}`;
      const llmResult = await llmService.generateJSON(systemPrompt, text);
      if (llmResult && typeof llmResult.aiProbability === 'number') {
        const aiScore = Math.round((1 - llmResult.aiProbability) * 100);
        return {
          aiProbability: llmResult.aiProbability,
          isLikelyAI: llmResult.isLikelyAI || llmResult.aiProbability > 0.6,
          confidence: llmResult.confidence || 'medium',
          indicators: llmResult.indicators || [],
          explanation: llmResult.explanation || '',
          aiScore
        };
      }
    } catch (err) {
      console.warn('[AITextDetector] LLM detection error, using NLP heuristics:', err.message);
    }

    // Fallback Stylistic Heuristics
    return this.heuristicDetect(text);
  }

  heuristicDetect(text) {
    const indicators = [];
    let aiProbPoints = 0;

    // AI Buzzword & Synthetic Structure checks
    const aiBuzzwords = [
      /\bdelve\b/i, /\btapestry\b/i, /\bmoreover\b/i, /\bfurthermore\b/i,
      /\btestament to\b/i, /\bpivotal\b/i, /\bparamount\b/i, /\bin summary\b/i,
      /\bin conclusion\b/i, /\bit's important to note\b/i, /\bseamlessly\b/i,
      /\bfostering\b/i, /\brealm\b/i, /\bbeacon\b/i, /\bmultifaceted\b/i
    ];

    let buzzwordCount = 0;
    aiBuzzwords.forEach(rgx => {
      if (rgx.test(text)) {
        buzzwordCount++;
      }
    });

    if (buzzwordCount >= 3) {
      aiProbPoints += 45;
      indicators.push(`High frequency of characteristic AI vocabulary (${buzzwordCount} matches found)`);
    } else if (buzzwordCount >= 1) {
      aiProbPoints += 20;
      indicators.push('Contains synthetic transition phrases common in AI outputs');
    }

    // AI Structured Marketing / Trading Funnel Pattern Check (ChatGPT default headers)
    const structuredHeaders = /\b(Strategy|Risk Management|Key Takeaways|The System:|Setup:|Daily net cumulative|Rules:|Execution:|Summary:)\b/i;
    const colonTitle = /^.+:\s*$/m.test(text) || text.includes('Exact System:');
    if (structuredHeaders.test(text) || colonTitle) {
      aiProbPoints += 55;
      indicators.push('Structured section header & colon formatting matching LLM generated marketing post output');
    }

    // Sentence length uniformity (low burstiness)
    const sentences = text.split(/(?<=[.!?])\s+/).filter(s => s.length > 5);
    if (sentences.length >= 4) {
      const lengths = sentences.map(s => s.split(/\s+/).length);
      const avg = lengths.reduce((a, b) => a + b, 0) / lengths.length;
      const variance = lengths.reduce((a, b) => a + Math.pow(b - avg, 2), 0) / lengths.length;
      const stdDev = Math.sqrt(variance);

      if (stdDev < 3.5 && avg > 12) {
        aiProbPoints += 25;
        indicators.push('Unusually uniform sentence length structure (low burstiness)');
      } else if (stdDev > 8) {
        indicators.push('Natural sentence length variation observed (high human burstiness)');
      }
    }

    // Formatting patterns: excessive bulleted list layout with bolded titles
    const bulletListPattern = /^[\s\t]*[*•-]\s*\*\*.*?\*\*/gm;
    const matches = text.match(bulletListPattern);
    if (matches && matches.length >= 3) {
      aiProbPoints += 25;
      indicators.push('Structured markdown list with bold headers matching LLM default output style');
    }

    // Reddit colloquialisms check (Human signals)
    const redditSlang = /\b(tldr|tl;dr|imo|imho|lmao|lol|afaik|fwiw|op|sub|edit:|yall|y'all|tbh|smh)\b/i;
    if (redditSlang.test(text) && !structuredHeaders.test(text)) {
      aiProbPoints -= 25;
      indicators.push('Contains authentic informal social media idioms & Reddit slang');
    }

    // Typos / casual punctuation (Human signals)
    const casualPunctuation = /\?\?|\!\!|\.\.\.|:\)|:\(/;
    if (casualPunctuation.test(text) && !structuredHeaders.test(text)) {
      aiProbPoints -= 15;
      indicators.push('Contains informal punctuation or expressive emojis/emoticons');
    }

    // Normalize probability
    const clampedProb = Math.min(0.95, Math.max(0.05, aiProbPoints / 100));
    const isLikelyAI = clampedProb >= 0.50;
    const aiScore = Math.round((1 - clampedProb) * 100);

    if (indicators.length === 0) {
      indicators.push('Standard stylistic profile without strong AI markers');
    }

    return {
      aiProbability: Number(clampedProb.toFixed(2)),
      isLikelyAI,
      confidence: sentences.length > 3 ? "medium" : "low",
      indicators,
      explanation: isLikelyAI 
        ? "Text exhibits multiple synthetic writing patterns characteristic of AI language models."
        : "Text shows natural stylistic variance consistent with human writing.",
      aiScore
    };
  }
}

module.exports = new AITextDetector();
